---
# This Playbook has to be called by this way 
#
# - role: rename_device
#   ideascube_id: "kb_bdi_tv5monde"
#   when: ansible_hostname == 'kb_mooc_vog_345'
# 
# With kb_bdi_tv5monde The new project name you would like to give
# With kb_mooc_vog_345 The existing project name


- include_vars: group_vars/{{ ansible_architecture }}.yml

- name: Set date and time 
  set_fact: date="{{ ansible_date_time["date"]}}" time="{{ ansible_date_time["time"]}}"

- name: Set an ideascubeName and generate an UUID
  set_fact: ideascubeName="{{ ideascube_id }}_{{ 1000 | random }}" 
    UUID="{{ ansible_default_ipv4["macaddress"] | hash('md5') }}"

- name: A way to get the public IP of the device
  shell: wget -qO- http://ipecho.net/plain ; echo
  register: public_ip

- name: Write all the variables in /etc/firstStart.csv 
  copy: content=id,{{ date }},{{ time }},{{ ideascubeName }},{{ UUID }},{{ ansible_default_ipv4["macaddress"] }},{{ ansible_default_ipv4["address"] }},{{ public_ip.stdout }}\n dest=/etc/firstStart.csv

- name: Send this file over the central_server 
  raw: cat /etc/firstStart.csv | ssh -p 443 {{ central_server }} "cat >> ./ansible/UUID/firstStart.csv"
  when: sync_log|bool

- name: Adding name to the hosts file
  lineinfile: dest=/etc/hosts regexp='^{{ hotspotip }}' insertafter='{{ hotspotip }}' 
    line='{{ hotspotip }} {{ ideascubeName |replace("_", "-") }}.lan {{ hostnameÂ }} {{ mook_front_server_name }}' 
    owner=root group=root mode=0644

- name: An hostname can not have _ so we are switching to -, python can not have - so using _ sometime too
  hostname: name={{ ideascubeName |replace("_", "-") }}

- name: Copy dnsmasq.conf file
  template: src=dnsmasq.conf.j2 dest=/etc/dnsmasq.conf backup=yes

- name: Copy hostapd.conf file
  template: src=hostapd.conf.j2 dest=/etc/hostapd/hostapd.conf owner=root group=root mode=755 backup=yes

- name: Copy hosts file
  template: src=hosts.j2 dest=/etc/hosts owner=root group=root mode=755 backup=yes

- name: Add IDEASCUBE_ID
  lineinfile: dest=/etc/default/ideascube
              regexp='^'
              line='IDEASCUBE_ID={{ ideascubeName }}'
              state=present

- name: Create entry to clone/pull git repository
  template: src=nm-dispatcher.j2 dest=/etc/NetworkManager/dispatcher.d/ansiblePullUpdate
    owner=root group=root mode=0755

- name: Job done, let's reboot now.
  command: reboot